import type { EnvironmentCatalog, EnvironmentOperation } from '../src/api/environmentTypes';
// Contract-only test inputs, never imported by production code.
export const environmentCatalog: EnvironmentCatalog = {
  settings: {
    install_root: '/srv/wsl/envs/managed',
    allowed_root: '/srv/wsl/envs',
    revision: 3,
    enabled: true,
    reason: null,
  },
  components: [
    {
      id: 'installer',
      name: '安装工具',
      description: '审核的安装器',
      version: 'locked-installer',
      detected_version: 'locked-installer',
      status: 'ready',
      location: '/srv/wsl/envs/managed/tool',
      kind: 'tool',
      group: 'tools',
      required: true,
      installable: true,
      download_bytes: 1024,
      installed_bytes: 4096,
      license: 'MIT',
      source_url: 'https://example.invalid/installer',
      checks: [{ name: '版本', ok: true, message: '已核对' }],
      problem: null,
      dependencies: [],
    },
    {
      id: 'base',
      name: '基础运行环境',
      description: 'PDF / RapidOCR / RDKit',
      version: 'locked-base',
      detected_version: null,
      status: 'missing',
      location: null,
      kind: 'runtime',
      group: 'base',
      required: true,
      installable: true,
      download_bytes: 2048,
      installed_bytes: null,
      license: 'Apache-2.0 / BSD',
      source_url: 'https://example.invalid/base',
      checks: [],
      problem: '解释器缺失',
      dependencies: ['installer'],
    },
    {
      id: 'decimer',
      name: 'DECIMER 运行时',
      description: '隔离结构识别',
      version: 'locked-decimer',
      detected_version: null,
      status: 'unchecked',
      location: null,
      kind: 'runtime',
      group: 'structure',
      required: true,
      installable: true,
      download_bytes: null,
      installed_bytes: null,
      license: 'MIT',
      source_url: 'https://example.invalid/decimer',
      checks: [],
      problem: null,
      dependencies: ['installer'],
    },
    {
      id: 'decimer-models',
      name: 'DECIMER 模型',
      description: '结构模型内容',
      version: 'locked-decimer-models',
      detected_version: null,
      status: 'partial',
      location: null,
      kind: 'models',
      group: 'structure',
      required: true,
      installable: true,
      download_bytes: 8192,
      installed_bytes: 1024,
      license: '模型许可',
      source_url: 'https://example.invalid/decimer-models',
      checks: [],
      problem: '指纹未核对',
      dependencies: ['decimer'],
    },
    {
      id: 'admet',
      name: 'ADMET CPU 运行时',
      description: 'CPU 推理',
      version: 'locked-admet',
      detected_version: null,
      status: 'unconfigured',
      location: null,
      kind: 'runtime',
      group: 'admet',
      required: false,
      installable: true,
      download_bytes: null,
      installed_bytes: null,
      license: 'MIT',
      source_url: 'https://example.invalid/admet',
      checks: [],
      problem: null,
      dependencies: ['installer'],
    },
    {
      id: 'admet-models',
      name: 'ADMET 模型',
      description: '预测模型',
      version: 'locked-admet-models',
      detected_version: null,
      status: 'incompatible',
      location: null,
      kind: 'models',
      group: 'admet',
      required: false,
      installable: false,
      download_bytes: null,
      installed_bytes: null,
      license: '模型许可',
      source_url: 'https://example.invalid/admet-models',
      checks: [],
      problem: '需运营方处理',
      dependencies: ['admet'],
    },
  ],
  presets: [
    {
      id: 'core',
      name: '推荐基础组合',
      description: '统一核心运行边界',
      component_ids: ['installer', 'base'],
    },
  ],
  checked_at: null,
  active_operation: null,
  operations: [],
};
export function prerequisiteCatalog(): EnvironmentCatalog {
  return {
    ...environmentCatalog,
    components: environmentCatalog.components.map((component) => ({
      ...component,
      installable: true,
      download_bytes:
        component.id === 'admet'
          ? 1_400_000_000
          : component.id === 'admet-models'
            ? 14_000_000
            : component.download_bytes,
    })),
  };
}
export const environmentOperation: EnvironmentOperation = {
  id: 'environment-operation-contract',
  request_id: 'request_contract_12345',
  action: 'install',
  component_ids: ['installer', 'base'],
  status: 'running',
  created_at: '2026-01-01T00:00:00Z',
  started_at: '2026-01-01T00:00:01Z',
  finished_at: null,
  install_root: environmentCatalog.settings.install_root,
  stage: 'verify',
  completed_components: ['installer'],
  log_tail: ['正在验证基础模块'],
  error: null,
  applied: false,
};
