import type {
  CSVPreview,
  Dataset,
  Molecule,
  MoleculeDrawing,
  Pair,
  Region,
  SARJob,
} from '../src/api/sarTypes';
import type {
  StudyContext,
  StudyFragment,
  StudyProfile,
  StudyReport,
  StudyRow,
} from '../src/api/sarStudyTypes';
export const sarDataset: Dataset = {
  id: 'dataset-control',
  title: '原始数据 draft',
  source_kind: 'project',
  source_project_id: 'project-control',
  source_sha256: 'a'.repeat(64),
  source_document_sha256: '9'.repeat(64),
  revision: 2,
  stale: false,
  row_count: 3,
  input_row_count: 4,
  eligible_count: 2,
  issue_count: 1,
  metrics: [
    {
      id: 'metric-control',
      name: 'IC50 原文',
      unit: 'nM',
      target: 'raw target',
      assay: 'raw assay',
    },
  ],
  created_at: '2026-10-08T12:00:00Z',
};
export const sarMolecule: Molecule = {
  id: 'reference/control',
  label: '原文 007B',
  smiles: '[13CH3][C@H](O)Cl',
  molfile: null,
  graph_sha256: 'c'.repeat(64),
  eligible: true,
  issues: [],
  observations: [
    {
      metric_id: 'metric-control',
      value: '<10',
      unit: 'nM',
      context: { target: 'raw target', assay: 'raw assay', duration: null },
      source_page: 8,
      source_row: 2,
      source_kind: 'patent',
    },
  ],
  source_compound_id: 'source/control',
  source_page: 7,
};
export const sarInvalid: Molecule = {
  ...sarMolecule,
  id: 'invalid/control',
  label: '原文 missing',
  smiles: null,
  graph_sha256: null,
  eligible: false,
  issues: ['missing_smiles', 'graph_conflict'],
  observations: [],
  source_page: null,
};
export const sarDrawing: MoleculeDrawing = {
  molecule: sarMolecule,
  svg: '<?xml version="1.0" encoding="iso-8859-1"?><svg xmlns="http://www.w3.org/2000/svg" xmlns:rdkit="http://www.rdkit.org/xml" width="400px" height="300px" viewBox="0 0 400 300"><path class="bond-0 atom-0 atom-1" d="M 80,150 L 200,150" style="fill:none;stroke:#000000;stroke-width:2px;stroke-linecap:butt"/></svg>',
  atoms: [
    { index: 0, element: 'C', x: 0.2, y: 0.5 },
    { index: 1, element: 'O', x: 0.5, y: 0.5 },
  ],
};
export const sarRegion: Region = {
  id: 'b'.repeat(32),
  dataset_id: sarDataset.id,
  molecule_id: sarMolecule.id,
  dataset_revision: 2,
  graph_sha256: sarMolecule.graph_sha256!,
  atom_indices: [1],
  attachment_count: 1,
  created_at: sarDataset.created_at,
};
export const sarJob: SARJob = {
  id: 'job-control',
  dataset_id: sarDataset.id,
  region_id: sarRegion.id,
  metric_id: 'metric-control',
  status: 'complete',
  processed: 3,
  total: 3,
  matched: 1,
  error_code: null,
  error_message: null,
  created_at: sarDataset.created_at,
  started_at: sarDataset.created_at,
  finished_at: sarDataset.created_at,
  input_sha256: 'd'.repeat(64),
  stale: false,
};
export const sarPair: Pair = {
  reference_id: sarMolecule.id,
  molecule_id: 'candidate/control',
  label: '原文 009',
  match_status: 'matched',
  reasons: ['raw_reason'],
  comparison: 'indeterminate',
  reference_values: ['<10 nM', '<10 nM'],
  candidate_values: ['5 nM'],
  fold_change: null,
  evidence_basis: 'insufficient',
};
export const csvPreview: CSVPreview = {
  token: 'e'.repeat(32),
  filename: '原始 导出.csv',
  headers: [
    'compound_id',
    'identifier_label',
    'smiles',
    'metric',
    'value',
    'unit',
    'target',
    'assay',
  ],
  row_count: 4,
  samples: [
    {
      compound_id: '原始/control',
      identifier_label: '007B',
      smiles: 'CCO',
      metric: 'IC50',
      value: '<10',
      unit: 'nM',
      target: '原始靶点',
      assay: '原始实验',
    },
  ],
  suggested_id: 'compound_id',
  suggested_smiles: 'smiles',
  suggested_activities: ['value'],
};
export const studyContext: StudyContext = {
  id: 'e'.repeat(64),
  metric_id: 'metric-control',
  name: 'IC50 原文',
  unit: 'nM',
  context: { assay: 'raw assay', target: 'raw target', cell_line: null },
  molecule_count: 2,
  observation_count: 3,
  distinct_value_count: 2,
  value_samples: ['<10', '5'],
};
export const studyJob: SARJob = { ...sarJob, id: 'study-control', kind: 'study' };
export const namedRegion: Region = { ...sarRegion, name: 'R1 用户原文', kind: 'variable' };
export const coreRegion: Region = {
  ...sarRegion,
  id: '8'.repeat(32),
  name: 'Core 原文',
  kind: 'core',
  atom_indices: [0],
};
export const studyProfile: StudyProfile = {
  dataset_id: sarDataset.id,
  dataset_revision: 2,
  contexts: [studyContext],
  regions: [namedRegion, coreRegion],
};
export const studyRow: StudyRow = {
  molecule_id: sarMolecule.id,
  label: sarMolecule.label,
  eligible: true,
  scaffold_id: 'core/control',
  values: { [studyContext.id]: ['<10', '<10'] },
  activity_status: { [studyContext.id]: 'indeterminate' },
  strong: false,
  properties: { molecular_weight: 120, Solubility_AqSolDB: null },
  property_origins: { molecular_weight: 'rdkit_computed', Solubility_AqSolDB: 'manual_null' },
  predictions: { hERG: 0.24 },
  prediction_origin: 'imported',
  pareto_front: 1,
  candidate_status: 'selected',
  priority_group: 1,
  selection_order: 1,
  coverage: 0.5,
  reasons: ['raw_reason 原文'],
};
export const studyFragment: StudyFragment = {
  id: 'fragment/control',
  smiles: '[1*]O',
  molecule_ids: [sarMolecule.id],
  molecule_count: 1,
  strong_count: 1,
  bins: [{ label: '<10', kind: 'censored', observations: 2, molecules: 1, strong: true }],
  better: 0,
  worse: 1,
  indeterminate: 1,
  missing: 0,
  is_reference: true,
};
export const studyReport: StudyReport = {
  schema_version: 1,
  dataset_id: sarDataset.id,
  dataset_revision: 2,
  title: '研究 original draft',
  input_sha256: studyJob.input_sha256,
  engine_sha256: '4'.repeat(64),
  research_only: true,
  article_algorithm_reproduced: false,
  molecule_count: 3,
  eligible_count: 2,
  observation_count: 4,
  strict_pair_count: 2,
  contexts: [studyContext],
  matched_pair_count: 1,
  comparable_pair_count: 1,
  policies: [
    {
      context_id: studyContext.id,
      direction: 'lower',
      grade_order: [],
      strong_threshold: 10,
      threshold_inclusive: true,
    },
  ],
  distributions: [
    {
      context_id: studyContext.id,
      bins: studyFragment.bins,
      observed_molecules: 2,
      observations: 3,
      missing_molecules: 1,
      unresolved_molecules: 1,
      strong_molecules: 1,
    },
  ],
  scaffolds: [
    {
      id: 'core/control',
      smiles: 'C',
      molecule_count: 2,
      strong_count: 1,
      bins: studyFragment.bins,
      molecule_ids: [sarMolecule.id],
      descriptive_only: true,
      assignment_kind: 'confirmed_core',
      core_region_id: coreRegion.id,
    },
  ],
  regions: [
    {
      region: namedRegion,
      reference_label: sarMolecule.label,
      reference_fragment_id: studyFragment.id,
      fixed_background_sha256: '5'.repeat(64),
      matched: 1,
      not_matched: 0,
      ambiguous: 1,
      ineligible: 0,
      comparable: 1,
      no_variation: true,
      independent_backgrounds: 1,
      fragments: [studyFragment],
    },
  ],
  candidates: [studyRow],
  rows: [],
  warnings: ['raw_warning 原文'],
  candidate_policy: 'strict-context-pareto-v1',
};
