"""Reproduce the packaged base-worker requirements from the sole application lock."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
from pathlib import Path

GENERATOR = "tools/build_environment_resources.py"


def rendered(root: Path, export: str) -> tuple[str, str]:
    source = hashlib.sha256((root / "uv.lock").read_bytes()).hexdigest()
    dependencies = {}
    for line in export.splitlines():
        match = re.match(r"^([A-Za-z0-9_.-]+)==([A-Za-z0-9_.+-]+)(?:\s|$)", line)
        if match:
            dependencies[match[1]] = match[2]
    if not {"pymupdf", "rdkit", "rapidocr-onnxruntime"} <= set(dependencies):
        raise ValueError(
            "The base-worker export must include its actual scientific consumers"
        )
    if any(
        line.startswith(("-e ", "file:", "http:", "--index-url", "--extra-index-url"))
        for line in export.splitlines()
    ):
        raise ValueError(
            "Base requirements must not introduce another dependency authority"
        )
    requirements = (
        f"# Generated by {GENERATOR}; do not edit.\n"
        f"# Canonical uv.lock SHA-256: {source}\n"
        "# PDF / RapidOCR / RDKit worker; Linux x86_64, CPython 3.12.\n"
        "# Derived runtime input, not a second application dependency lock.\n"
        + export.rstrip()
        + "\n"
    )
    manifest = {
        "schema_version": 1,
        "generator": GENERATOR,
        "lock_sha256": source,
        "python": "3.12",
        "distributions": dependencies,
        "requirements_sha256": hashlib.sha256(requirements.encode()).hexdigest(),
    }
    return requirements, json.dumps(manifest, indent=2, sort_keys=True) + "\n"


def build(root: Path, uv: str, *, check: bool = False) -> None:
    version = subprocess.run(
        [uv, "--version"], check=True, capture_output=True, text=True, timeout=10
    )
    if not version.stdout.startswith("uv 0.11.31 "):
        raise ValueError(
            "Use the controller-pinned uv 0.11.31 to reproduce environment resources"
        )
    exported = subprocess.run(
        [
            uv,
            "export",
            "--frozen",
            "--no-dev",
            "--no-emit-project",
            "--no-header",
            "--no-annotate",
            "--format",
            "requirements.txt",
        ],
        cwd=root,
        capture_output=True,
        text=True,
        check=True,
        timeout=60,
    )
    requirements, manifest = rendered(root, exported.stdout)
    destination = root / "src" / "patent_sar_extractor" / "defaults" / "environments"
    expected = {"base-requirements.txt": requirements, "base-runtime.json": manifest}
    if destination.is_symlink() or not destination.resolve().is_relative_to(
        root.resolve()
    ):
        raise ValueError(
            "Environment resources must remain within their source package"
        )
    previous_manifest = destination / "base-runtime.json"
    if previous_manifest.exists():
        previous = json.loads(previous_manifest.read_text())
        current_requirements = destination / "base-requirements.txt"
        if (
            previous.get("generator") != GENERATOR
            or not current_requirements.is_file()
            or current_requirements.is_symlink()
            or hashlib.sha256(current_requirements.read_bytes()).hexdigest()
            != previous.get("requirements_sha256")
        ):
            raise ValueError(
                "Generated environment resources were modified; preserve them before rebuilding"
            )
    for name, value in expected.items():
        target = destination / name
        if check:
            if (
                target.is_symlink()
                or not target.is_file()
                or target.read_text() != value
            ):
                raise ValueError(
                    "Packaged base-worker requirements differ from the canonical lock"
                )
        else:
            if target.is_symlink():
                raise ValueError("Environment resources cannot be symbolic links")
            destination.mkdir(parents=True, exist_ok=True)
            target.write_text(value, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--uv", default="uv")
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    try:
        build(Path(__file__).resolve().parents[1], arguments.uv, check=arguments.check)
    except (ValueError, OSError, subprocess.SubprocessError) as error:
        parser.exit(1, f"Environment resources failed: {error}\n")
    print(
        "Canonical base environment resources verified."
        if arguments.check
        else "Canonical base environment resources generated."
    )


if __name__ == "__main__":
    main()
