"""Bundle verified Vite output into the installed application's static assets."""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import tempfile
from pathlib import Path

GENERATOR = "tools/build_frontend.py"
MARKER = ".bundle.json"
MAX_BYTES = 64 * 1024 * 1024
EXTENSIONS = {
    ".html",
    ".js",
    ".css",
    ".svg",
    ".png",
    ".ico",
    ".json",
    ".woff2",
    ".md",
    ".wasm",
}


def fingerprints(directory: Path, *, managed: bool = False) -> dict[str, str]:
    files: dict[str, str] = {}
    size = 0
    for path in sorted(directory.rglob("*")):
        if path.is_symlink():
            raise ValueError("Web build output must not contain symbolic links")
        if not path.is_file():
            continue
        relative = path.relative_to(directory).as_posix()
        if managed and relative == MARKER:
            continue
        if path.suffix not in EXTENSIONS or relative == MARKER:
            raise ValueError(f"Unexpected Web build file: {relative}")
        size += path.stat().st_size
        if size > MAX_BYTES:
            raise ValueError("Web bundle exceeds 64 MiB")
        files[relative] = hashlib.sha256(path.read_bytes()).hexdigest()
    return files


def discard_staged_bundle(root: Path) -> None:
    staged = root / "build" / "lib" / "patent_sar_extractor" / "web" / "static"
    if any(
        path.is_symlink()
        for path in (staged, *staged.parents)
        if path.is_relative_to(root)
    ):
        raise ValueError("Staged Web build directories must not be symbolic links")
    if not staged.resolve().is_relative_to(root.resolve()):
        raise ValueError("Staged Web build must remain inside the repository")
    if not staged.exists():
        return
    marker = staged / MARKER
    if not marker.is_file() or marker.is_symlink():
        raise ValueError(
            "Staged Web bundle is unmanaged; preserve it before rebuilding"
        )
    previous = json.loads(marker.read_text(encoding="utf-8"))
    if previous.get("generator") != GENERATOR or previous.get("files") != fingerprints(
        staged, managed=True
    ):
        raise ValueError(
            "Staged Web bundle was modified; preserve it before rebuilding"
        )
    # Setuptools copies changed files but otherwise retains obsolete hashed assets.
    # Delete only this exact, unmodified generated copy, not the whole build tree.
    shutil.rmtree(staged)


def bundle(root: Path, *, check: bool = False) -> None:
    source = root / "frontend" / "dist"
    destination = root / "src" / "patent_sar_extractor" / "web" / "static"
    if not source.resolve().is_relative_to(
        root.resolve()
    ) or not destination.resolve().is_relative_to(root.resolve()):
        raise ValueError("Web build directories must remain inside the repository")
    if source.is_symlink() or destination.is_symlink():
        raise ValueError("Web build directories must not be symbolic links")
    if not (source / "index.html").is_file():
        raise ValueError(
            "Build the frontend first: cd frontend && npm ci && npm run build"
        )
    files = fingerprints(source)
    if not any(name.endswith(".js") for name in files):
        raise ValueError("Web bundle has no executable application assets")
    metadata = {"generator": GENERATOR, "files": files}
    if destination.exists():
        marker = destination / MARKER
        if not marker.is_file() or marker.is_symlink():
            raise ValueError(
                "Existing static directory is unmanaged; preserve it before bundling"
            )
        previous = json.loads(marker.read_text(encoding="utf-8"))
        if previous.get("generator") != GENERATOR or previous.get(
            "files"
        ) != fingerprints(destination, managed=True):
            raise ValueError(
                "Existing generated assets were modified; preserve them before bundling"
            )
        if check:
            if previous != metadata:
                raise ValueError(
                    "Packaged Web assets differ from the current frontend build"
                )
            return
    elif check:
        raise ValueError("Packaged Web assets are missing")
    discard_staged_bundle(root)
    destination.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="x-patentsar-bundle-") as workspace:
        temporary = Path(workspace) / "static"
        shutil.copytree(source, temporary)
        (temporary / MARKER).write_text(
            json.dumps(metadata, indent=2) + "\n", encoding="utf-8"
        )
        # Only an exact, unmodified bundle generated by this tool is replaced.
        if destination.exists():
            shutil.rmtree(destination)
        shutil.copytree(temporary, destination)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        bundle(Path(__file__).resolve().parents[1], check=args.check)
    except (OSError, ValueError) as error:
        parser.exit(1, f"Web bundle failed: {error}\n")
    print(
        "Web bundle verified."
        if args.check
        else "Web bundle prepared for wheel packaging."
    )


if __name__ == "__main__":
    main()
